name: CI/CD-Demo
on:
  push:
   branches: master
   
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
           name: artifact
           path: ${{github.workspace}}/*
